image:
  repository: docker.elastic.co/logstash/logstash
  tag: "8.12.0"
  pullPolicy: IfNotPresent

env:
  LS_JAVA_OPTS: "-Xms256m -Xmx256m"

kafka:
  bootstrapServers: "kafka:9092"
  topic: "bank-logs"

elasticsearch:
  url: "http://elasticsearch:9200"

resources: {}
