image:
  repository: "notifications-service"
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources: {}

env:
  SPRING_APPLICATION_NAME: "notifications-service"
  SPRING_PROFILES_ACTIVE: "k8s"
  JAVA_OPTS: "-Xms128m -Xmx256m"

  # Kafka-настройки (по-хорошему переопределяются в values-dev/test/prod)
  KAFKA_BOOTSTRAP_SERVERS: "bank-kafka:9092"
  KAFKA_TOPIC_NOTIFICATIONS: "bank.notifications"
  KAFKA_NOTIFICATIONS_GROUP: "notifications-service"
