image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: "8.12.0"
  pullPolicy: IfNotPresent

service:
  port: 9200

resources: {}

env:
  discovery_type: "single-node"
  xpack.security.enabled: "false"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
