apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer
  namespace: {{ .Release.Namespace }}
  labels: { app: transfer }
spec:
  replicas: 1
  selector: { matchLabels: { app: transfer } }
  template:
    metadata:
      labels: { app: transfer }
    spec:
      containers:
        - name: transfer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"
            - name: SPRING_APPLICATION_NAME
              value: "{{ .Values.env.SPRING_APPLICATION_NAME }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"
            - name: KAFKA_TOPIC_NOTIFICATIONS
              value: "{{ .Values.env.KAFKA_TOPIC_NOTIFICATIONS }}"
            - name: ACCOUNTS_BASE_URL
              value: "{{ .Values.env.ACCOUNTS_BASE_URL }}"
            - name: EXCHANGE_BASE_URL
              value: "{{ .Values.env.EXCHANGE_BASE_URL }}"
            - name: NOTIFICATIONS_BASE_URL
              value: "{{ .Values.env.NOTIFICATIONS_BASE_URL }}"

            - name: OAUTH2_TOKEN_URI
              value: "{{ .Values.env.OAUTH2_TOKEN_URI }}"
            - name: OAUTH2_JWK_SET_URI
              value: "{{ .Values.env.OAUTH2_JWK_SET_URI }}"
            - name: OAUTH2_CLIENT_ID
              value: "{{ .Values.env.OAUTH2_CLIENT_ID }}"
            - name: OAUTH2_CLIENT_SECRET
              valueFrom: { secretKeyRef: { name: transfer-secrets, key: OAUTH2_CLIENT_SECRET } }

          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true

          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3

          resources: {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: app-config
          configMap:
            name: transfer-app-config
            items:
              - key: application.yml
                path: application.yml
