server:
  port: 8080

spring:
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/token
            jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs
        registration:
          transfer:
            provider: keycloak
            client-id: transfer-service
            authorization-grant-type: client_credentials

gateway:
  base-url: http://gateway:8080

# ======================================
#  Micrometer Tracing + Zipkin
# ======================================
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
    probes.enabled: true

  # ---- ACTUATOR + METRICS ----
  metrics:
    enable:
      all: true

  # ---- TRACING ----
  tracing:
    sampling:
      probability: 1.0

  # ---- ZIPKIN ----
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.consul.config: DEBUG
    org.springframework.cloud.consul: DEBUG
    org.springframework.web: INFO
    io.micrometer: INFO