spring:
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            token-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/token
            jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs
        registration:
          transfer:
            provider: keycloak
            client-id: transfer-service
            authorization-grant-type: client_credentials

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all          # для at-least-once
      retries: 3
    properties:
      spring.json.trusted.packages: "com.example.dto"
      spring.json.add.type.headers: false

gateway:
  base-url: http://gateway:8080

app:
  kafka:
    notifications-topic: ${KAFKA_TOPIC_NOTIFICATIONS:bank.notifications}

management:
  endpoints:
    web:
      exposure:
        include: health,info
