image:
  repository: "exchange-service"
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources: {}

env:
  SPRING_APPLICATION_NAME: "exchange-service"
  SPRING_PROFILES_ACTIVE: "k8s"
  JAVA_OPTS: "-Xms128m -Xmx256m"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs"
