server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: exchange-service
      auto-offset-reset: latest
      enable-auto-commit: true     # at most once â†’ commit BEFORE processing
    properties:
      spring.json.trusted.packages: "com.example.dto"
  application:
    name: exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  kafka:
    exchange-topic: ${KAFKA_TOPIC_EXCHANGE_RATES:bank.exchange-rates}
    exchange-group: exchange-service

logging:
  level:
    org.springframework.security: INFO
