server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: exchange-service
      auto-offset-reset: latest
      enable-auto-commit: true     # at most once â†’ commit BEFORE processing
    properties:
      spring.json.trusted.packages: "com.example.dto"
  application:
    name: exchange-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs

# ======================================
#  Micrometer Tracing + Zipkin
# ======================================
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
    probes.enabled: true

  # ---- ACTUATOR + METRICS ----
  metrics:
    enable:
      all: true

  # ---- TRACING ----
  tracing:
    sampling:
      probability: 1.0

  # ---- ZIPKIN ----
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

app:
  kafka:
    exchange-topic: ${KAFKA_TOPIC_EXCHANGE_RATES:bank.exchange-rates}
    exchange-group: exchange-service

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.consul.config: DEBUG
    org.springframework.cloud.consul: DEBUG
    org.springframework.web: INFO
    io.micrometer: INFO
