server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      acks: 1        # at most once
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.trusted.packages: "com.example.dto"
  application:
    name: exchange-generator-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/token
            jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs
        registration:
          generator:
            provider: keycloak
            client-id: exchange-generator
            authorization-grant-type: client_credentials

exchange:
  base-url: http://gateway:8080

# ======================================
#  Micrometer Tracing + Zipkin
# ======================================
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
    probes.enabled: true

  # ---- ACTUATOR + METRICS ----
  metrics:
    enable:
      all: true

  # ---- TRACING ----
  tracing:
    sampling:
      probability: 1.0

  # ---- ZIPKIN ----
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

app:
  kafka:
    exchange-topic: ${KAFKA_TOPIC_EXCHANGE_RATES:bank.exchange-rates}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.consul.config: DEBUG
    org.springframework.cloud.consul: DEBUG
    org.springframework.web: INFO
    io.micrometer: INFO
