server:
  port: 8080

spring:
  application:
    name: blocker-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs

blocker:
  random-block-percent: 3        # вероятность блокировки, %
  night-start-hour: 0            # 0..23 (UTC)
  night-end-hour: 6
  night-amount-threshold: 50000  # всё что >= — подозрительно ночью
  max-amount: 1000000            # защитный порог

# ======================================
#  Micrometer Tracing + Zipkin
# ======================================
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
    probes.enabled: true

  # ---- ACTUATOR + METRICS ----
  metrics:
    enable:
      all: true

  # ---- TRACING ----
  tracing:
    sampling:
      probability: 1.0

  # ---- ZIPKIN ----
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.consul.config: DEBUG
    org.springframework.cloud.consul: DEBUG
    org.springframework.web: INFO
    io.micrometer: INFO