image:
  repository: "transfer-service"
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  port: 8080

resources: {}

env:
  SPRING_APPLICATION_NAME: "transfer-service"
  SPRING_PROFILES_ACTIVE: "k8s"
  JAVA_OPTS: "-Xms128m -Xmx256m"
  ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  # Внутрисетевые DNS сервисов (НЕ через Spring Cloud Gateway)
  ACCOUNTS_BASE_URL: "http://accounts.bank-dev.svc:8080"
  EXCHANGE_BASE_URL:  "http://exchange.bank-dev.svc:8080"
  NOTIFICATIONS_BASE_URL: "http://notifications.bank-dev.svc:8080"

  KAFKA_BOOTSTRAP_SERVERS: "bank-kafka:9092"
  KAFKA_TOPIC_NOTIFICATIONS: "bank.notifications
  LOG_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  LOG_KAFKA_TOPIC: "bank-logs"

  # OAuth2 (client-credentials)
  OAUTH2_TOKEN_URI: "http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/token"
  OAUTH2_JWK_SET_URI: "http://keycloak-keycloak.bank-dev.svc:8080/realms/bank/protocol/openid-connect/certs"
  OAUTH2_CLIENT_ID: "transfer-service"

secrets:
  OAUTH2_CLIENT_SECRET: "HGp9JPlchvXfYcyqqvLeZTDZIJOwxFLL"
