apiVersion: v1
kind: Service
metadata:
  name: cash
  namespace: {{ .Release.Namespace }}
  labels: { app: cash }
spec:
  selector: { app: cash }
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
  type: ClusterIP
