apiVersion: v1
kind: Secret
metadata:
  name: accounts-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "{{ .Values.secrets.SPRING_DATASOURCE_PASSWORD }}"
  KEYCLOAK_ADMIN_CLIENT_SECRET: "{{ .Values.secrets.KEYCLOAK_ADMIN_CLIENT_SECRET }}"
