apiVersion: v1
kind: Secret
metadata:
  name: exchange-generator-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  OAUTH2_CLIENT_SECRET: "{{ .Values.secrets.OAUTH2_CLIENT_SECRET }}"
