image:
  repository: prom/prometheus
  tag: "v2.53.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

resources: {}

bankServices:
  - name: accounts
    port: 8080
  - name: cash
    port: 8080
  - name: transfer
    port: 8080
  - name: exchange
    port: 8080
  - name: exchange-generator
    port: 8080
  - name: blocker
    port: 8080
  - name: notifications
    port: 8080
  - name: gateway
    port: 8080
