image:
  repository: "bitnami/kafka"
  tag: "3.7.0-debian-12-r0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 9092

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

kafka:
  brokerId: 0
  advertisedListener: "kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
  logRetentionHours: 168

topics:
  - name: bank.notifications
    partitions: 3
    replicationFactor: 1
  - name: bank.exchange-rates
    partitions: 1
    replicationFactor: 1
