# helm/Chart.yaml
apiVersion: v2
name: bank
description: Umbrella chart for bank microservices
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: keycloak
    version: 0.1.0
    repository: "file://charts/keycloak"
    condition: keycloak.enabled
  - name: postgres
    version: 0.1.0
    repository: "file://charts/postgres"
    condition: postgres.enabled
  - name: accounts
    version: 0.1.0
    repository: "file://charts/accounts"
    condition: accounts.enabled
  - name: notifications
    version: 0.1.0
    repository: "file://charts/notifications"
    condition: notifications.enabled
  - name: blocker
    version: 0.1.0
    repository: "file://charts/blocker"
    condition: blocker.enabled
  - name: cash
    version: 0.1.0
    repository: "file://charts/cash"
    condition: cash.enabled
  - name: transfer
    version: 0.1.0
    repository: "file://charts/transfer"
    condition: transfer.enabled
  - name: exchange
    version: 0.1.0
    repository: "file://charts/exchange"
    condition: exchange.enabled
  - name: exchange-generator
    version: 0.1.0
    repository: "file://charts/exchange-generator"
    condition: exchangeGenerator.enabled
  - name: edge
    version: 0.1.0
    repository: "file://charts/edge"
    condition: edge.enabled
