apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: {{ .Release.Namespace }}
  labels: { app: notifications }
spec:
  replicas: 1
  selector: { matchLabels: { app: notifications } }
  template:
    metadata:
      labels: { app: notifications }
    spec:
      containers:
        - name: notifications
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: ZIPKIN_ENDPOINT
              value: "{{ .Values.env.ZIPKIN_ENDPOINT }}"
            - name: SPRING_CONFIG_ADDITIONAL_LOCATION
              value: "file:/config/"
            - name: SPRING_APPLICATION_NAME
              value: "{{ .Values.env.SPRING_APPLICATION_NAME }}"
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ .Values.env.SPRING_PROFILES_ACTIVE }}"
            - name: JAVA_OPTS
              value: "{{ .Values.env.JAVA_OPTS }}"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "{{ .Values.env.KAFKA_BOOTSTRAP_SERVERS }}"
            - name: KAFKA_TOPIC_NOTIFICATIONS
              value: "{{ .Values.env.KAFKA_TOPIC_NOTIFICATIONS }}"
            - name: KAFKA_NOTIFICATIONS_GROUP
              value: "{{ .Values.env.KAFKA_NOTIFICATIONS_GROUP }}"
            - name: LOG_KAFKA_TOPIC
              value: "{{ .Values.env.LOG_KAFKA_TOPIC }}"
          volumeMounts:
            - name: app-config
              mountPath: /config
              readOnly: true
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
          resources: {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: app-config
          configMap:
            name: notifications-app-config
            items:
              - key: application.yml
                path: application.yml
